### ISSUE TITLE
IPv6 for every jail

### ISSUE THREAD

**Issue by msimerson** [msimerson/Mail-Toaster-6#257]
### Expected behavior

Every jail gets provisioned with IPv4 and IPv6 IPs.

### Observed behavior

Every jail gets provisioned with IPv4 only.

### Steps to reproduce

Install, as normal.

### TODO

* [x] add JAIL_NET6
    * [x] assign random [global prefix](http://simpledns.com/private-ipv6.aspx)
* [x] add get_jail_ip6 in #256
* [x] add get_reverse_ip6
* [x] host: extend pf rules
* [x] add ip6.addr to /etc/jail.conf when provisioning
* [x] add ip6.addr to /etc/jail.conf when re-provisioning
* [x] dns: add IPv6 forward and reverse DNS to data/dns/mt6-local
* [x] dns: add IPv6 nameserver address to /etc/resolv.conf
* [x] redis: comment out bind directive, so listens on IPv6 too
* [x] clamav: bind to all IPs (restore default)
* [x] start doing it, and figure out what else goes here

**Comment by Infern1** [comment]
I have ipv6 on the outside and forward ipv6 to my internal ipv4 hosts.

**Comment by msimerson** [comment]
Until now I've just been slapping my public IPv6 addresses onto the public NIC. Still subject to firewall rules, but no NAT/RDR. Eventually that's going to bite me as there's bound to be IPv6 addresses stuffed into config files all over the place. It'll be better to make them deterministic sooner than later.

**Comment by msimerson** [comment]
This might work:

````
$ get_jail_ip6 dns
fd7a:e5cd:1fc1:c221:dead:beef:cafe:0003
$ get_jail_ip6 redis
fd7a:e5cd:1fc1:c221:dead:beef:cafe:0010
$ get_jail_ip6 elasticsearch
fd7a:e5cd:1fc1:c221:dead:beef:cafe:001b
````

**Comment by msimerson** [comment]
- [ ] mysqld: binds only to a single IP, or all of them.
    - Consider adding `[mysqld] bind-address: ::` to listen on all addresses
    - GRANT statements would need updating. 👎
