### ISSUE TITLE
spam & ham (bayesian) training

### ISSUE THREAD

**Issue by msimerson** [msimerson/Mail-Toaster-6#258]
### Expected behavior

- moving messages from inbox to spam should train rspamd as spam
- moving messages from spam folder to inbox should train rspamd as ham
- bonus points if the solution trains spamassassin too

### Observed behavior

nothing happens.

### Steps to reproduce

Move messages between mailboxes.

### TODO

* ~~get dovecot's [managesieve](https://wiki2.dovecot.org/Pigeonhole/ManageSieve/Configuration) working~~ moved to #263
* [x] train as spam messages moved into .Junk
* [x] train as ham messages moved out of .Junk
* [x] train as ham messages moved to .Archive
* [x] assign a password to rspamd controller
    * ~~embed rspamd password in training scripts~~
    * [x] add dovecot jail IPs to rspamd secure_ip list

### References

* [https://wiki2.dovecot.org/HowTo/AntispamWithSieve](https://wiki2.dovecot.org/HowTo/AntispamWithSieve)
* [Pigeonhole/ManageSieve/Configuration](https://wiki2.dovecot.org/Pigeonhole/ManageSieve/Configuration)

**Comment by Infern1** [comment]
Have a cron job in the rspamd jail to train HAM and SPAM, notice rspamd doing a good job when it's trained. But the method above sounds even better, however don't get any messages anymore in the .Spam folder

**Comment by msimerson** [comment]
If your mailfilter files made their way over to MT6 and you still have SpamAssassin setting X-Spam-Status, then some of them should. Mine still do. 

There's another issue lurking in there. Old toasters used .Spam and all newer clients are using the standard .Junk instead.

**Comment by msimerson** [comment]
> Have a cron job in the rspamd jail to train HAM and SPAM

Is that working similarly to the learning in MT5?

**Comment by Infern1** [comment]
> If your mailfilter files made their way over to MT6 and you still have SpamAssassin setting X-Spam-Status, then some of them should. Mine still do.

Yes mailfilter still the same

>There's another issue lurking in there. Old toasters used .Spam and all newer clients are using the standard .Junk instead.

I symlink .Spam to .Junk... not the best method but works...

**Comment by Infern1** [comment]
> Is that working similarly to the learning in MT5?
No direct commands in some mailboxes with high traffic

**Comment by msimerson** [comment]
What triggers the learn process? How does the cron job know what to train?

**Comment by msimerson** [comment]
The learn-[ham|spam].sh scripts called by dovecot sieve to train rspamd are ridiculously simple:

````
exec /usr/local/bin/curl -XPOST -H "Password: *******" --data-binary @- http://172.16.15.13:11334/learnspam
````

I won't be that easy for spamassassin. :-(  (might have to install spamassassin in dovecot jail to get the sa-learn binary).

**Comment by Infern1** [comment]
> What triggers the learn process? How does the cron job know what to train?

me going into the rspamd jail and executing the lean process... no automation

**Comment by msimerson** [comment]
I think Dovecot may have a way to deal with the .Spam -> .Junk transition. I'm not entirely sure, but I *think* [this change](https://github.com/msimerson/Mail-Toaster-6/pull/256/commits/90e19035ed130c447fad929c85df8c85b9ec02d0) basically makes the .Spam folder an alias of .Junk. That needs some further [looking into](https://wiki2.dovecot.org/Namespaces) by a brain less cloudy than mine is at present.

**Comment by msimerson** [comment]
fixed in #256
