### ISSUE TITLE
spamassassin: add data partition

### ISSUE THREAD

**Issue by msimerson** [msimerson/Mail-Toaster-6#83]
### Expected behavior
- preserve custom config files across deployments
### Observed behavior
- no provisions to use custom config files
### TODO
- [x] add data partition
- [x] install config files to /data/spamassassin/etc
- [x] use /data/spamassassin/db for SA DB dir
